name: Acceptance

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    concurrency:
      group: acceptance-tests-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 60
    steps:
    - name: Install Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go

    - uses: actions/checkout@v3

    - name: Install Terraform 1.5.7
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7
        terraform_wrapper: false

    - name: Export Terraform CLI Path
      run: echo "TF_ACC_TERRAFORM_PATH=$(which terraform)" >> "$GITHUB_ENV"

    - name: Run tests
      run: |
        TF_ACC=1 go test -v ./... -parallel=16 -count=1 -timeout=45m
      env:
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
